language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "oOXayI9t7Vfn8JFdEEVl3tVomJbXhkHxXcGjMMG6YvXYMKUVEHeFc13yHu9ykBk8hx6m52HkEZ17zrC/PjIaZWW59Hfj+fSTFxM5ie1cz8lN3/kS/8NF2kuJLmco3QPTxNWwxsv5OOeJ7AjRzKcdEUCfykUwJs7C8YHrLOHvE8yF755UA3kQkROekOyV+4WSEKEXMx1PjU9Sbjk0gBRAG+bv+s1xBP7G+xyGnMmsjYiv1T/QEOuxMEfCgyuzD2h9+p4UqJXYPcJHsc2w8JVfuHMHxgKH0CBjNQqfGcfRh4APw6cpjKB+g+Uqz5tMQ46ka0FCF+p3oku8WImIPVvFGpHI8pM8zziLEE6nEYG1CB/wefvSrZhE2SontoJIqay8DbeNofOJVL6KS8NVlsqWJpira2QXHZi/jHNgjIxH086rgFn0F4Y6ovevlnsZSMbCnKJgpQMxONfkd61k09PH+nmMowXpAreEbvazHShGixKdaWOWpeqj0Lgiv1zm0JbSJMyebfNaCw+TriAFGA8m21Um7wsVzSZQqesA02Ew5k5y+JlYg2cQu4wJ2LAWbKTOg68iCteJQp5KO8u5h6pV1METlj0cXp9h4ZsMdkSK9kLwnoIxJWtkj4gry+8QqaJe8N8c1Wm8SiFJllwi4ajpC1oT5WOiSQ5r9VStv6eb6GQ="
